### ISSUE TITLE
Feature Request: Add Support for Manga Converted Through Mokuro

### ISSUE THREAD

**Issue by HoodedTissue** [mathewthe2/immersion_reader#14]
In regards to manga immersion apps on iOS, the only one that exists is [KantanManga](https://github.com/juanj/KantanManga). However, because this app requires you to manually drag a box to OCR text, it is quite clunky as sometimes the OCR is unreliable, resulting in the user having to re-select the text 2 - 3 times before all the correct characters are detected. 

Because manually having to OCR each textbox is unfavorable, I think it would be a great addition if support for manga converted through [Mokuro](https://github.com/kha-white/mokuro) is added. Mokuro basically does all the OCRing for the user (OCR is almost perfect, out of all the manga I have converted with Mokuro, I think I have only ever needed to change 2 or so characters) and converts the manga into an html page where the textboxes have select-able text. There are also tools to convert such html pages into [pdfs](https://github.com/Kartoffel0/Mokuro2Pdf).

**Comment by mathewthe2** [comment]
Both pdf and html support is available through the browser. And I have tested it with manga converted through Mokuro.

if you have trouble paying for the browser feature on the app store, feel free to build the app using the source code here.
