### ISSUE TITLE
Dictionary (partially) not working

### ISSUE THREAD

**Issue by GriefBacon** [mathewthe2/immersion_reader#2]
The popup dictionary feature isn’t working beyond the preface in the book I’m currently reading. 

- Preface has no problem, but when I check Ch. 1 and beyond, the feature doesn’t work.

- Can’t replicate this bug in other books I have loaded into the app

- I tried downloading the problematic epub file from a different site - same result.

**Comment by mathewthe2** [comment]
Are the text rendered images or some quote block?

I can't say without you sending the file to me by email or other means that don't produce a digital copy of copyrighted work.
