### ISSUE TITLE
how can i use other dictionaries?

### ISSUE THREAD

**Issue by mannfuri** [mathewthe2/immersion_reader#24]
love this app

**Comment by mathewthe2** [comment]
In settings of the app.

It doesn't support v3 / structured content yet, but the old dictionaries would work.

**Comment by mannfuri** [comment]
ok、完成しました、完璧です！
ありがとうございます！
![image](https://github.com/mathewthe2/immersion_reader/assets/91338215/15e6fac7-aeea-448f-889c-bdb40d0fca69)
