### ISSUE TITLE
Bookmark automatically set when importing book

### ISSUE THREAD

**Issue by trd-db** [mathewthe2/immersion_reader#6]
I have an epub for a book I'm reading, and upon loading it and going to the first chapter, the progress bar jumps to 25% and I cannot set a new bookmark before that point (this happens whether auto bookmark is on or off). So whenever I open the book, it goes to the 25% mark no matter where I was before it. 

Tested with ttsu reader on the web with the same epub, and did not experience this issue.

**Comment by mathewthe2** [comment]
Please provide extra information.

- Ios device
- Ios version
- Immersion Reader version
- steps to reproduce
- Ebook name
- Videos if it's helpful

**Comment by trd-db** [comment]
Device: iPhone 14 Pro
OS: iOS 16.1.2
Immersion reader version: 1.3b
Ebook name: また、同じ夢を見ていた
Steps: Load ebook into reader, go to the begging of chapter 1 in the book, see the percentage jump to 25%, exit app. Open app, and reopen the book and it will open to the 25% bookmark that was added automatically. 

Video included

https://user-images.githubusercontent.com/15252953/210188847-f5dfc911-a55c-4ac3-9746-19380d681cb9.MOV

**Comment by mathewthe2** [comment]
Can't reproduce with the epub files that I have. Have you tried manually setting the bookmark elsewhere? 

Can you reproduce even after reinstalling the app?

**Comment by trd-db** [comment]
I have tried reinstalling and still have the same issue. Manually trying to set a bookmark doesn't appear to do anything.

**Comment by mathewthe2** [comment]
Assuming this is only n issue for this epub file, have you tried the following setup?

- TTU reader on Safari browser on iPhone
- TTU reader on Immersion Reader browser
