### ISSUE TITLE
Improve text selection reliability

### ISSUE THREAD

**Issue by mathewthe2** [mathewthe2/immersion_reader#7]
## Issue

Text selection is unreliable

## Reason

Selection relies on caretRangeFromPoint and range.startOffset, which selects the next character when the cursor selects around 70% of the previous character.

https://github.com/birchill/10ten-ja-reader/blob/fbbbde5c429f1467a7b5a938e9d67597d7bd5ffa/src/content/get-text.ts#L248

## Suggestion

Adjust position by getting the bounding box of the _previous_ character and see if point is within that bounding box. If yes, use _previous_ character.

**Comment by mathewthe2** [comment]
Related issue
https://github.com/lrorpilla/jidoujisho/issues/133

**Comment by lrorpilla** [comment]
Hey @mathewthe2, thanks for pointing this out to me. 

I've modified the JavaScript I inject accordingly with the reference you posted above **[here](https://github.com/lrorpilla/jidoujisho/blob/f6cfc8d1ecc9a871b8309b77fbb3b5f8ea248ae3/yuuna/lib/src/pages/implementations/reader_ttu_source_page.dart#L449-L640)**.
